id: I61DE885E
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:13:17.374353'
last_modified: '2022-06-18T20:13:17.374369'
parser: null
source_metadata:
  title: Vajrakīla maṇḍala ritual by Bla ma dam pa (block print), colophon excerpt
  author: bla ma dam pa bsod nams rgyal mtshan/
  description: 'Digital version 1.0 {Wylie}, diplomatic edition of witness A; WYLIE
    COPY of master xml (completed: 2020-06-03); revised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4880
  bases:
    157b:
      title: Vajrakīla maṇḍala ritual by Bla ma dam pa (block print), colophon excerpt
      order: 1
      base_file: 157b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
